### ISSUE TITLE
Image File Size Issues

### ISSUE THREAD

**Issue by co221133** [InventivetalentDev/CustomSkins#3]
Hey guys. I've never successfully uploaded a skin either with the website or with the commands, so I'm entirely new to this. But I've been trying to upload two skins, one 64x64 (my preferred one) and one 64x32. Both sizes (uploaded to imgur) return the error of "invalid file size." I thought 64x32 was the size that was needed; is there something I'm missing? I'll attach the two skins to this post.
![monsterhunter_v2](https://cloud.githubusercontent.com/assets/20447487/23106184/b6d62b56-f69e-11e6-803a-efd12d80c7e2.png)
![monsterhunter_basic](https://cloud.githubusercontent.com/assets/20447487/23106185/bb16d666-f69e-11e6-881a-82a5ea566ceb.png)

**Comment by InventivetalentDev** [comment]
When you're uploading to Imgur, make sure you specify the direct link to the image (e.g. https://i.imgur.com/UXUq0BW.png) instead of the website url (e.g. https://imgur.com/a/D341f)

**Comment by co221133** [comment]
Perfect, thank you very much! :) Didn't realize I had to open it in its own tab, I was using the copied links.
