### ISSUE TITLE
Little problem...

### ISSUE THREAD

**Issue by Ezzcargot** [InventivetalentDev/CustomSkins#4]
Hi ! I'm Nathan, and I love your work. I have try all your plugins (exept api). But for my server, I need your custom skins plugin, but there is a bug... Sometimes, all players are "refreshing", there inventory cases are set to the first, and they didn't see anything, and to fix it, they a contrains to do F3+A. Is it possible to resolve it ?
Thank you very much and sorry for my english.
Nathan

**Comment by InventivetalentDev** [comment]
If there was a way to resolve that I'd have probably implemented it already.
No, there is no way I know of to get rid of this occasional glitch, so you'll have to stay with F3+A until Mojang hopefully fixes the client.
