### ISSUE TITLE
/applyCustomSKin

### ISSUE THREAD

**Issue by kahmad1000** [InventivetalentDev/CustomSkins#6]
Hello
After uploading the skin when I want to apply it with /applycustomskin it doesn't work and giving me an error:
unhandled exception, see console for details: unhandled exception while invoking command method is v1.1.0#applyskin
what should I do?

**Comment by Loapu** [comment]
Ich habe das gleiche Problem ^^ Wäre nett, wenn du helfen könntest, Haylee  👍
